LAB3/Models/ShoppingCart.cs
namespace LAB3.Models
{
    public class ShoppingCart
    {
        public List<CartItem> Items { get; set; } = new List<CartItem>();
        public void AddItem(CartItem item)
        {
            var existingItem = Items.FirstOrDefault(i => i.ProductId ==
            item.ProductId);
            if (existingItem != null)
            {
                existingItem.Quantity += item.Quantity;
            }
            else
            {
                Items.Add(item);
            }
        }

        
        public void RemoveItem(int productId)
        {
            Items.RemoveAll(i => i.ProductId == productId);
        }


        public void UpdateItem(CartItem cartItem)
        {
            // Tìm kiếm mục trong giỏ hàng dựa trên ID sản phẩm
            var existingItem = Items.FirstOrDefault(x => x.ProductId == cartItem.ProductId);

            if (existingItem != null)
            {
                // Cập nhật số lượng
                existingItem.Quantity = cartItem.Quantity;
            }
            else
            {
                // Thêm mục mới nếu không tìm thấy
                Items.Add(cartItem);
            }
        }
    }
}

LAB3/Controllers/ShoppingCartController.cs
using LAB3.Extensions;
using LAB3.Models;
using LAB3.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LAB3.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IProductRepository _productRepository;
        public ShoppingCartController(IProductRepository productRepository, ApplicationDbContext context,UserManager<ApplicationUser> userManager)
        {
            _productRepository = productRepository;
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            // Giả sử bạn có phương thức lấy thông tin sản phẩm từ productId
            var product = await GetProductFromDatabase(productId);
            var cartItem = new CartItem
            {
                ProductId = productId,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity,
                ImageUrl = product.ImageUrl
            };
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new ShoppingCart();
            cart.AddItem(cartItem);
            HttpContext.Session.SetObjectAsJson("Cart", cart);
            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new ShoppingCart();
            return View(cart);  
        }
        // Các actions khác.
        //
        //
        //
        // ..
        private async Task<Product> GetProductFromDatabase(int productId)
        {
            // Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
            var product = await _productRepository.GetByIdAsync(productId);
            return product;
        }



        public IActionResult RemoveFromCart(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart is not null)
            {
                cart.RemoveItem(productId);

                // Lưu lại giỏ hàng vào Session sau khi đã xóa mục
                HttpContext.Session.SetObjectAsJson("Cart", cart);
            }

            return RedirectToAction("Index");
        }


        public IActionResult Checkout()
        {
            return View(new Order());
        }




        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart == null || !cart.Items.Any())
            {
                // Xử lý giỏ hàng trống...
                return RedirectToAction("Index");
            }
            var user = await _userManager.GetUserAsync(User);
            order.UserId = user.Id;
            order.OrderDate = DateTime.UtcNow;
            order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
            order.OrderDetails = cart.Items.Select(i => new OrderDetail
            {
                ProductId = i.ProductId,
                Quantity = i.Quantity,
                Price = i.Price
            }).ToList();
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove("Cart");
            return View("OrderCompleted", order); // Trang xác nhận hoànthành đơn hàng
        }





        [HttpPost]
        public IActionResult IncreaseQuantityInCart(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");

            if (cart is null || !cart.Items.Any())
            {
                // Xử lý giỏ hàng trống (hiển thị thông báo hoặc chuyển hướng)
                return RedirectToAction("Index");
            }

            var cartItem = cart.Items.FirstOrDefault(item => item.ProductId == productId);

            if (cartItem is null)
            {
                // Xử lý sản phẩm không tồn tại trong giỏ hàng (hiển thị thông báo)
                return RedirectToAction("Index");
            }

            cartItem.Quantity++;

            // Cập nhật giỏ hàng
            HttpContext.Session.SetObjectAsJson("Cart", cart);

            return RedirectToAction("Index");
        }



        [HttpPost]
        public IActionResult DecreaseQuantityInCart(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");

            if (cart is null || !cart.Items.Any())
            {
                // Xử lý giỏ hàng trống (hiển thị thông báo hoặc chuyển hướng)
                return RedirectToAction("Index");
            }

            var cartItem = cart.Items.FirstOrDefault(item => item.ProductId == productId);

            if (cartItem is null)
            {
                // Xử lý sản phẩm không tồn tại trong giỏ hàng (hiển thị thông báo)
                return RedirectToAction("Index");
            }

            cartItem.Quantity--;

            // Cập nhật giỏ hàng
            HttpContext.Session.SetObjectAsJson("Cart", cart);

            return RedirectToAction("Index");
        }

        public IActionResult ClearCart()
        {
            HttpContext.Session.Remove("Cart");
            return RedirectToAction("Index");
        }

    }
}

LAB3/Views/ShoppingCart/Checkout.cshtml
@model Order
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Checkout</h2>
<form asp-action="Checkout" method="post">
    <div class="form-group">
        <label asp-for="ShippingAddress">Shipping Address</label>
        <input asp-for="ShippingAddress" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Notes">Notes</label>
        <textarea asp-for="Notes" class="form-control"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Place Order</button>
</form>

LAB3/Views/ShoppingCart/Index.cshtml
@model LAB3.Models.ShoppingCart
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="h-100" style="background-color: #eee;">
    <div class="container h-100 py-5">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-10">

                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
                    <div>
                        <p class="mb-0">
                            <span class="text-muted">Sort by:</span> <a href="#!" class="text-body">
                                price <i class="fas fa-angle-down mt-1"></i>
                            </a>
                        </p>
                    </div>
                </div>
                @foreach(var item in Model.Items)
                {
                    <div class="card rounded-3 mb-4">
                        <div class="card-body p-4">
                            <div class="row d-flex justify-content-between align-items-center">
                                <div class="col-md-2 col-lg-2 col-xl-2">
                                    <img src="@item.ImageUrl"
                                         class="img-fluid rounded-3" alt="Cotton T-shirt">
                                </div>
                                <div class="col-md-3 col-lg-3 col-xl-3">
                                    <p class="lead fw-normal mb-2">@item.Name</p>
                                </div>
                                <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                    <form method="post" action="@Url.Action("IncreaseQuantityInCart", "ShoppingCart")">
                                        <input type="hidden" name="productId" value="@item.ProductId">
                                        <button type="submit" class="btn btn-sm btn-primary"><i class="bi bi-plus-lg"></i></button>
                                    </form>
                                    <input type="number" class="form-control" asp-for="@item.Quantity" min="1" />
                                    <form method="post" action="@Url.Action("DecreaseQuantityInCart", "ShoppingCart")">
                                        <button type="submit" class="btn btn-sm btn-primary"><i class="bi bi-dash-lg"></i></button>
                                        <input type="hidden" name="productId" value="@item.ProductId">
                                    </form>
                                </div>
                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                    <h5 class="mb-0">@(item.Price * item.Quantity)</h5>
                                </div>
                            </div>
                        </div>
                    </div>

                }
               
                <div class="card">
                    <div class="card-body">
                        <form action="@Url.Action("Checkout", "ShoppingCart")">
                            <button type="submit" class="btn btn-primary">Check Out</button>
                        </form>
                    </div>
                    <div class="card-body">
                        <form method="post" action="@Url.Action("ClearCart", "ShoppingCart")">
                            <button type="submit" class="btn btn-danger">Xóa Tất Cả</button>
                        </form>
                    </div>

                    
                </div>

            </div>
        </div>
    </div>
</section>

LAB3/Views/ShoppingCart/OrderCompleted.cshtml
@model LAB3.Models.Order
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Order Completed</h2>
<p>Your order has been placed successfully with total price: @Model.TotalPrice</p>